-
    version: 1.2.13.{build}
    os: Windows Server 2012 R2
    platform: Any CPU
    configuration: Release
    before_build:
        - nuget restore src/log4net.vs2012.sln
    build:
        project: src/log4net.vs2012.sln
    after_test:
        - nuget pack src\log4net.vs2012.csproj -version %APPVEYOR_BUILD_VERSION% -Properties "Configuration=Release;Platform=AnyCPU" -Symbols
        - appveyor PushArtifact log4net-await.%APPVEYOR_BUILD_VERSION%.nupkg
        - appveyor PushArtifact log4net-await.%APPVEYOR_BUILD_VERSION%.symbols.nupkg
